export {default as getPosts} from "./getPosts.js"
export {default as getPostById} from "./getPostById.js"
export {default as addPost} from "./addPost.js"
export {default as editPost} from "./editPost.js"
export {default as deletePost} from "./deletePost.js"